export const EXAMPLE_ELEMENT_FETCHED = 'elements.EXAMPLE_ELEMENT_FETCHED';
export const ELEMENT_FETCHED = 'elements.ELEMENT_FETCHED';
export const ELEMENT_WITH_CHILD_VIEWS_FETCHED = 'elements.ELEMENT_WITH_CHILD_VIEWS_FETCHED';
